# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
