# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0003_exchange_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange_rate',
            options={'verbose_name_plural': 'Exchange Rate'},
        ),
        migrations.AlterField(
            model_name='exchange_rate',
            name='currency',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
